version: '2'
services:
  testnetsuivi-app:
    image: testnetsuivi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testnetsuivi-postgresql:5432/testNETSUIVI
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8100:8100
  testnetsuivi-postgresql:
    extends:
      file: postgresql.yml
      service: testnetsuivi-postgresql
